run:
  concurrency: 8
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-dirs:
    - bin
    - tmp

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - typecheck
    - unused
