name: Go CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.head.ref || github.ref_name }}  # Use PR source branch or push branch

        - name: Debug checkout
          run: |
            echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
            echo "Repository contents:"
            ls -la
            echo "GitHub Event Name: ${{ github.event_name }}"
            echo "GitHub Ref: ${{ github.ref }}"
            echo "GitHub Head Ref: ${{ github.event.pull_request.head.ref }}"

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23'
            cache: true

        - name: Build
          run: |
                pwd
                ls -la
                mkdir -p ./bin
                go build -o ./bin/pdfjuicer ./cmd

        - name: Test
          run: go test -v ./...

  linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}  # Use PR source branch or push branch

      - name: Debug checkout
        run: |
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Repository contents:"
          ls -la

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          args: --timeout=5m
